#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Sun Oct 15 16:41:51 2017
@author:  vr308
"""
import numpy as np
import matplotlib.pylab as plt

M = 3
cov = np.identity(3)
x = np.sort(np.random.uniform(-8,8, 200))


def sample_paths(x, cov, gamma):
    w=np.matrix(np.random.multivariate_normal([0,0,0],cov)).T
    Phi = np.matrix([phi_gauss(x, -4, gamma), phi_gauss(x, 0, gamma), phi_gauss(x, 4, gamma)]).T
    f_x = np.matmul(Phi,w)
    return f_x
    
def phi_gauss(x,m, gamma):
    return np.exp(-gamma*np.square(x - m))
    
   
mu = [-4,0,4.0]
gamma = [0.2,0.2,0.2]
x = np.sort(np.random.uniform(-8,8, 200))
plt.figure(figsize=(8,8))
plt.subplot(211)
for i in np.arange(0,len(mu)):
    plt.plot(x, phi_gauss(x,mu[i], gamma[i]), label= '($\mu_{%d}$,$\gamma_{%d}$) = [%d, %.2f]'%(i+1,i+1, mu[i], gamma[i]))
plt.title('Basis space $\Phi = [\phi_{1}(x), \phi_{2}(x), \phi_{3}(x)]$', fontsize='small')
plt.legend(fontsize='x-small')
plt.xlabel('$x$')
plt.ylabel('$\phi_{i}(x)$')
plt.subplot(212)
for i in np.arange(1,7):
    plt.plot(x, sample_paths(x, cov, gamma[0]))
plt.title('Sample curves $f(x) = \sum_{i=1}^{3}w_{i}\phi_{i}(x)$ generated by sampling $\mathbf{w} \sim N(0,1I)$ from its prior dist.', fontsize='small')
plt.xlabel('$x$')
plt.ylabel('$f(x)$')